---
name: Clean Self-Hosted Runner and Containers
description: A Github Action to clean the workspace on a self-hosted runner

branding:
  icon: 'trash'
  color: 'orange'

inputs:
  service_ids:
    required: false
    default: ${{ toJSON(job.services.*.id) }}

runs:
  using: composite
  steps:
    - name: Build or use cached image
      shell: bash
      run: |
        IMAGE_NAME="davidantaki-actions-clean:latest"
        
        # Try to use existing image, build if not found
        if ! docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
          echo "Image not found locally, building from Dockerfile..."
          docker build -t "$IMAGE_NAME" "${{ github.action_path }}"
        else
          echo "Using existing image: $IMAGE_NAME"
        fi
        
        # Run the container
        docker run --rm \
          -v "/var/run/docker.sock":"/var/run/docker.sock" \
          -v "${{ github.workspace }}":"/github/workspace" \
          -e CLEAN_WORKSPACE="${{ env.CLEAN_WORKSPACE }}" \
          -e PROTECTED_CONTAINER_SERVICE_IDS="${{ inputs.service_ids }}" \
          -e GITHUB_ACTIONS=true \
          -e CI=true \
          --workdir /github/workspace \
          "$IMAGE_NAME"
